// items.js
import * as productImage from '../../Drawables/Products/index';
export const items = [
    {
      id: 1,
      category: "TOYS",
      name: "RC KIT",
      price: "168.90",
      image: productImage.a1,
    },
    {
      id: 2,
      category: "KEYBOARD",
      name: "Keycaps",
      price: "210.15",
      image: productImage.a2,
    },
    {
        id: 3,
        category: "HEADPHONES",
        name: "SKULL CANDY 2.0",
        price: "178.99",
        image: productImage.a3,
      },
      {
        id: 4,
        category: "HEADSET",
        name: "SAMSUNG EARPHONES",
        price: "9.99",
        image: productImage.a4,
      },
      {
        id: 5,
        category: "LAPTOP",
        name: "MACBOOK PRO",
        price: "1900.95",
        image: productImage.a5,
      },
      {
        id: 6,
        category: "SMARTPHONES",
        name: "SAMSUNG FOLD",
        price: "799.99",
        image: productImage.a6,
      },
      {
        id: 7,
        category: "MISC",
        name: "SKATEBOARD",
        price: "76.51",
        image: productImage.a7,
      },
      {
        id: 8,
        category: "CLOTHINGS",
        name: "PUMA CAP",
        price: "26.20",
        image: productImage.a8,
      },
      {
        id: 1,
        category: "TOYS",
        name: "RC KIT",
        price: "168.90",
        image: productImage.a1,
      },
      {
        id: 2,
        category: "KEYBOARD",
        name: "Keycaps",
        price: "210.15",
        image: productImage.a2,
      },
      {
          id: 3,
          category: "HEADPHONES",
          name: "SKULL CANDY 2.0",
          price: "178.99",
          image: productImage.a3,
        },
        {
          id: 4,
          category: "HEADSET",
          name: "SAMSUNG EARPHONES",
          price: "9.99",
          image: productImage.a4,
        },
        {
          id: 5,
          category: "LAPTOP",
          name: "MACBOOK PRO",
          price: "1900.95",
          image: productImage.a5,
        },
        {
          id: 6,
          category: "SMARTPHONES",
          name: "SAMSUNG FOLD",
          price: "799.99",
          image: productImage.a6,
        },
        {
          id: 7,
          category: "MISC",
          name: "SKATEBOARD",
          price: "76.51",
          image: productImage.a7,
        },
        {
          id: 8,
          category: "CLOTHINGS",
          name: "PUMA CAP",
          price: "26.20",
          image: productImage.a8,
        },
        {
          id: 1,
          category: "TOYS",
          name: "RC KIT",
          price: "168.90",
          image: productImage.a1,
        },
        {
          id: 2,
          category: "KEYBOARD",
          name: "Keycaps",
          price: "210.15",
          image: productImage.a2,
        },
        {
            id: 3,
            category: "HEADPHONES",
            name: "SKULL CANDY 2.0",
            price: "178.99",
            image: productImage.a3,
          },
          {
            id: 4,
            category: "HEADSET",
            name: "SAMSUNG EARPHONES",
            price: "9.99",
            image: productImage.a4,
          },
          {
            id: 5,
            category: "LAPTOP",
            name: "MACBOOK PRO",
            price: "1900.95",
            image: productImage.a5,
          },
          {
            id: 6,
            category: "SMARTPHONES",
            name: "SAMSUNG FOLD",
            price: "799.99",
            image: productImage.a6,
          },
          {
            id: 7,
            category: "MISC",
            name: "SKATEBOARD",
            price: "76.51",
            image: productImage.a7,
          },
          {
            id: 8,
            category: "CLOTHINGS",
            name: "PUMA CAP",
            price: "26.20",
            image: productImage.a8,
          },
          {
            id: 1,
            category: "TOYS",
            name: "RC KIT",
            price: "168.90",
            image: productImage.a1,
          },
          {
            id: 2,
            category: "KEYBOARD",
            name: "Keycaps",
            price: "210.15",
            image: productImage.a2,
          },
          {
              id: 3,
              category: "HEADPHONES",
              name: "SKULL CANDY 2.0",
              price: "178.99",
              image: productImage.a3,
            },
            {
              id: 4,
              category: "HEADSET",
              name: "SAMSUNG EARPHONES",
              price: "9.99",
              image: productImage.a4,
            },
            {
              id: 5,
              category: "LAPTOP",
              name: "MACBOOK PRO",
              price: "1900.95",
              image: productImage.a5,
            },
            {
              id: 6,
              category: "SMARTPHONES",
              name: "SAMSUNG FOLD",
              price: "799.99",
              image: productImage.a6,
            },
            {
              id: 7,
              category: "MISC",
              name: "SKATEBOARD",
              price: "76.51",
              image: productImage.a7,
            },
            {
              id: 8,
              category: "CLOTHINGS",
              name: "PUMA CAP",
              price: "26.20",
              image: productImage.a8,
            },
  ];
  